import { AnalyticsService } from './analytics.service.js';
import { MailerService } from './mailer.service.js';

/**
 * 6.2 — Weekly KPI report.
 *
 * Aggregates the headline metrics from AnalyticsService and renders them as a
 * compact HTML email. Designed to be invoked from a node-cron schedule
 * (every Monday at 10:00) but also exposes runManually() for verification.
 */
export class WeeklyReportService {
  constructor(
    private readonly analytics: AnalyticsService,
    private readonly mailer: MailerService,
  ) {}

  /** Build + send the weekly report. Returns true if sent, false otherwise. */
  async runManually(toOverride?: string): Promise<boolean> {
    if (!this.mailer.isEnabled) {
      console.warn('[WeeklyReport] Mailer not enabled — skipping send');
      return false;
    }

    const [financial, engagement, onboarding, safety] = await Promise.all([
      this.analytics.getFinancialKpis(),
      this.analytics.getEngagementKpis(),
      this.analytics.getOnboardingFunnel(),
      this.analytics.getSafetyStats(),
    ]);

    const subject = `[Nigar AI] Weekly KPI Report — ${new Date().toISOString().slice(0, 10)}`;
    const html = renderHtml({ financial, engagement, onboarding, safety });
    const text = renderText({ financial, engagement, onboarding, safety });

    return this.mailer.send({ to: toOverride, subject, html, text });
  }
}

// -------- Renderers --------

function renderHtml(args: {
  financial: any;
  engagement: any;
  onboarding: any;
  safety: any;
}): string {
  const { financial, engagement, onboarding, safety } = args;
  const safetyBadge =
    safety.unhandled > 0
      ? `<span style="background:#e74c3c;color:#fff;padding:2px 8px;border-radius:10px;font-weight:600">URGENT</span>`
      : `<span style="background:#27ae60;color:#fff;padding:2px 8px;border-radius:10px;font-weight:600">OK</span>`;

  const row = (label: string, value: string | number) =>
    `<tr><td style="padding:8px 12px;color:#7f8c8d;">${label}</td><td style="padding:8px 12px;font-weight:600;text-align:right;">${value}</td></tr>`;

  return `<!DOCTYPE html>
<html><body style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#f5f6fa;padding:24px;color:#2c3e50;">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);">
    <div style="background:#c0392b;color:#fff;padding:20px 24px;">
      <h1 style="margin:0;font-size:20px;">📊 Nigar AI — Weekly KPI Report</h1>
      <div style="opacity:0.85;font-size:13px;margin-top:4px;">${new Date().toUTCString()}</div>
    </div>

    <div style="padding:20px 24px;">
      <h3 style="margin-top:0;color:#2c3e50;">💰 Financial</h3>
      <table style="width:100%;border-collapse:collapse;">
        ${row('Total Revenue', `${financial.totalRevenue} AZN`)}
        ${row('ARPU', `${financial.arpu} AZN`)}
        ${row('LTV', `${financial.ltv} AZN`)}
        ${row('Paying Users', `${financial.payingUsers} / ${financial.totalUsers} (${financial.payingUserRatio}%)`)}
        ${row('Outstanding Credits', `${financial.outstandingCredits} AZN`)}
      </table>

      <h3 style="color:#2c3e50;margin-top:24px;">📈 Engagement</h3>
      <table style="width:100%;border-collapse:collapse;">
        ${row('Total Users', engagement.totalUsers)}
        ${row('DAU / WAU / MAU', `${engagement.dau} / ${engagement.wau} / ${engagement.mau}`)}
        ${row('Stickiness (DAU/MAU)', `${engagement.stickiness}%`)}
        ${row('Avg messages / session', engagement.avgMessagesPerSession)}
        ${row('New users today', engagement.newUsersToday)}
      </table>

      <h3 style="color:#2c3e50;margin-top:24px;">🎯 Onboarding</h3>
      <table style="width:100%;border-collapse:collapse;">
        ${row('Completion rate', `${onboarding.completionRate}%`)}
        ${row('Completed / Total', `${onboarding.completed} / ${onboarding.total}`)}
      </table>

      <h3 style="color:#2c3e50;margin-top:24px;">🆘 Safety ${safetyBadge}</h3>
      <table style="width:100%;border-collapse:collapse;">
        ${row('Total crisis events', safety.totalCrises)}
        ${row('Unhandled', `<span style="color:${safety.unhandled > 0 ? '#e74c3c' : '#27ae60'};">${safety.unhandled}</span>`)}
        ${row('Active conversations (1h)', safety.activeConversations)}
      </table>

      <p style="margin-top:24px;font-size:12px;color:#95a5a6;">
        Auto-generated by AdminPanel cron · weekly-report.service
      </p>
    </div>
  </div>
</body></html>`;
}

function renderText(args: {
  financial: any;
  engagement: any;
  onboarding: any;
  safety: any;
}): string {
  const { financial, engagement, onboarding, safety } = args;
  return [
    `Nigar AI — Weekly KPI Report (${new Date().toISOString().slice(0, 10)})`,
    '',
    'FINANCIAL',
    `  Revenue: ${financial.totalRevenue} AZN`,
    `  ARPU: ${financial.arpu} AZN  |  LTV: ${financial.ltv} AZN`,
    `  Paying users: ${financial.payingUsers}/${financial.totalUsers} (${financial.payingUserRatio}%)`,
    `  Outstanding credits: ${financial.outstandingCredits}`,
    '',
    'ENGAGEMENT',
    `  Users: ${engagement.totalUsers}`,
    `  DAU/WAU/MAU: ${engagement.dau}/${engagement.wau}/${engagement.mau}`,
    `  Stickiness: ${engagement.stickiness}%`,
    `  Avg msgs/session: ${engagement.avgMessagesPerSession}`,
    `  New today: ${engagement.newUsersToday}`,
    '',
    'ONBOARDING',
    `  Completion rate: ${onboarding.completionRate}%`,
    `  ${onboarding.completed}/${onboarding.total}`,
    '',
    'SAFETY',
    `  Total: ${safety.totalCrises}`,
    `  Unhandled: ${safety.unhandled}`,
    `  Active convos (1h): ${safety.activeConversations}`,
  ].join('\n');
}
